name: marx
description: A feature-packed discord bot written in Dart. For commies only.
version: 1.0.0
homepage: https://marx.bashvie.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  nyxx: ^1.1.0
  nyxx_commander: ^1.0.1
  yaml: ^2.2.1
  postgres: ^2.2.0

dependency_overrides:
  nyxx:
    git:
      url: https://github.com/l7ssha/nyxx.git
      ref: "1.1"
      path: nyxx
  http:
    git:
      url: git://github.com/dart-lang/http.git
  logging:
    git:
      url: git://github.com/dart-lang/logging.git
  http_parser:
    git:
      url: git://github.com/dart-lang/http_parser.git
  nyxx_commander:
    git:
      url: https://github.com/l7ssha/nyxx.git
      ref: "1.1"
      path: nyxx.commander

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
